# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rbenv-version", "README.md", "Rakefile"]
highlighter: pygments

title : stephendicato.com
email : stephendicato@gmail.com
name : Stephen DiCato
github_username : dicato
baseurl: ""
url : http://stephendicato.com/
markdown: kramdown
